Repository Frondgle/thearchive-server, pull requests merged in 2023-09, with the labels that each got.

#1 setting up pylint and folders
  .gitignore
  .pylintrc
  Pipfile
  manage.py
  settings.json
  thearchive/__init__.py
  thearchive/asgi.py
  thearchive/settings.py
  thearchive/urls.py
  thearchive/wsgi.py
  thearchiveapi/__init__.py
  thearchiveapi/admin.py
  thearchiveapi/apps.py
  thearchiveapi/migrations/__init__.py
  thearchiveapi/models/__init__.py
  thearchiveapi/tests.py
  thearchiveapi/views/__init__.py
Labels: good first issue

#3 Models ag
  scratch.sql
  seed_database.sh
  thearchiveapi/migrations/0001_initial.py
  thearchiveapi/models/__init__.py
  thearchiveapi/models/art.py
  thearchiveapi/models/fan.py
  thearchiveapi/models/tag.py
Labels: good first issue

#5 installed fixtures
  seed_database.sh
  thearchiveapi/fixtures/art.json
  thearchiveapi/fixtures/fans.json
  thearchiveapi/fixtures/tags.json
  thearchiveapi/migrations/0001_initial.py
  thearchiveapi/models/art.py
Labels: good first issue

#20 ArtViewSet-aj
  tests/__init__.py
  tests/art_tests.py
  thearchive/urls.py
  thearchiveapi/views/__init__.py
  thearchiveapi/views/art.py
  thearchiveapi/views/tag.py
Labels: help wanted

#22 trying to understand cloudinary--this is not correct
  thearchive/settings.py
  thearchiveapi/migrations/0001_initial.py
  thearchiveapi/models/art.py
  thearchiveapi/views/art.py
Labels: bug
